# Use the right terminal so vim theme works
set -g default-terminal "screen-256color"

# Use xclip to copy to system clipboard
# Use pbcopy to copy to system clipboard
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# Enable RGB colour if running in xterm(1)
set-option -sa terminal-overrides ",xterm*:Tc"

# enable OSC 52 clipboard
# https://medium.freecodecamp.org/tmux-in-practice-integration-with-system-clipboard-bcd72c62ff7b
# set -g set-clipboard on

# get rid of delay with esc key
set -sg escape-time 0

# resizing panes with the mouse
set-option -g mouse on

# Don't rename windows automatically (to preserve custom pane names)
# set-option -g allow-rename off

# remap prefix key
unbind C-b
set-option -g prefix C-w
bind-key C-w send-prefix

# split panes using v and s. Open new panes in same directory.
bind c new-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Switch panes with h/j/k/l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resizing panes
bind C-h resize-pane -L 5
bind C-j resize-pane -D 5
bind C-k resize-pane -U 5
bind C-l resize-pane -R 5

# Use vi keys in copy mode
setw -g mode-keys vi

# v to begin selection, y to yank to system clipboard
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# Mouse drag auto-copies to system clipboard
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

bind r source-file ~/.tmux.conf

# Status bar
set -g status-style 'bg=green fg=black'
set -g status-left ' #S '
set -g status-left-length 30
set -g status-right ' #(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "no git") | %H:%M '
set -g status-right-length 60
